## How to create Basic Array

In [1]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [2]:
np.ones(2)

array([1., 1.])

In [3]:
np.zeros(2)

array([0., 0.])

In [5]:
np.empty(4)

array([0., 0., 0., 0.])

In [6]:
np.arange(4)

array([0, 1, 2, 3])

In [7]:
np.arange(2,18,4)

array([ 2,  6, 10, 14])

In [9]:
np.linspace(10,5,4)

array([10.        ,  8.33333333,  6.66666667,  5.        ])

In [10]:
np.ones(4,dtype=np.int64)

array([1, 1, 1, 1], dtype=int64)

## Adding, Removing and Sorting Elements

In [11]:
arr = ([2, 1, 5, 3, 7, 4, 6, 8])
arr

[2, 1, 5, 3, 7, 4, 6, 8]

In [13]:
arr.sort()
arr

[1, 2, 3, 4, 5, 6, 7, 8]

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [18]:
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
a= a[np.newaxis,:]

In [33]:
a.ndim

2

In [34]:
a.size

4

In [35]:
a.shape

(1, 4)

In [30]:
x = np.array([[1,2,3,4],[4,5,6,8]])
np.concatenate((x,a),axis=0)

array([[1, 2, 3, 4],
       [4, 5, 6, 8],
       [1, 2, 3, 4]])

In [36]:
np.concatenate((x,a),axis=0).shape

(3, 4)

## Reshape an Array

In [44]:
a = np.arange(18)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [45]:
a.reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [47]:
np.reshape(a, newshape=(1, 18), order='C')

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17]])

## How to convert a 1D array into a 2D array

In [54]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [55]:
a.ndim

1

In [56]:
a.shape

(6,)

In [57]:
a.size

6

In [58]:
a = a[np.newaxis,:]

In [59]:
a

array([[0, 1, 2, 3, 4, 5]])

In [60]:
a.ndim

2

In [61]:
a.shape

(1, 6)

In [63]:
col_vector = a[:,np.newaxis]

In [64]:
col_vector

array([[[0, 1, 2, 3, 4, 5]]])

In [66]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [67]:
# another way
row_vector = np.expand_dims(a,axis=0)
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [71]:
row_vector.shape

(1, 6)

In [69]:
col_vector = np.expand_dims(a,axis=1)
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [70]:
col_vector.shape

(6, 1)

## Indexing and Slicing

In [72]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
data[2]

2

In [74]:
data[2:8]

array([2, 3, 4, 5, 6, 7])

In [75]:
data[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
data[-2:]

array([8, 9])

In [77]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
a.ndim

2

In [79]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [83]:
a[a<=5]

array([1, 2, 3, 4, 5])

In [84]:
# dividible by 2
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [85]:
a = np.array([[[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
             [[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]])
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [87]:
a.ndim

3

In [88]:
a[a<5]

array([1, 2, 3, 4, 1, 2, 3, 4])

In [89]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
(a > 5) | (a == 5)

array([[[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [91]:
b = np.nonzero(a<5)
b

(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [ ]:
# np.nonzero left reminder

## How to create an array from existing data

In [92]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
a1 = a[3:8]
a1

array([4, 5, 6, 7, 8])

In [94]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

In [96]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [97]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [98]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [99]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [100]:
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

## Basic array operations

In [101]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data+ones

array([2, 3])

In [102]:
data+2

array([3, 4])

In [103]:
data*4

array([4, 8])

In [104]:
data/data

array([1., 1.])

In [105]:
data*data

array([1, 4])

In [106]:
data.sum()

3

In [107]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [108]:
b.sum(axis=0)

array([3, 3])

In [109]:
b.sum(axis=1)

array([2, 4])

## Booradcasting and useful operations

In [111]:
data = np.array([1.0, 2.0])
data

array([1., 2.])

In [114]:
data = data*1.6
data

array([1.6, 3.2])

In [115]:
data.max()

3.2

In [116]:
data.min()

1.6

In [117]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [118]:
a.sum(axis=0)

array([1.12378257, 1.04875507, 1.01034462, 1.67669614])

In [119]:
a.sum(axis=1)

array([1.51832856, 1.55434556, 1.78690428])

In [120]:
a.max(axis=0)

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

In [121]:
a.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [122]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [123]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])