## 1D Array

In [3]:
import numpy as np
a = np.array([5,5,5,5,])
a

array([5, 5, 5, 5])

In [4]:
type(a)

numpy.ndarray

In [7]:
len(a)

4

In [8]:
a[1]

5

In [10]:
a[0:]

array([5, 5, 5, 5])

In [24]:
np.zeros(2)

array([0., 0.])

In [25]:
np.ones(2)

array([1., 1.])

In [26]:
np.empty(2)

array([1., 1.])

In [31]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
np.arange(3,18)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [36]:
np.arange(3,19,3)

array([ 3,  6,  9, 12, 15, 18])

In [37]:
np.linspace(2,19,4)

array([ 2.        ,  7.66666667, 13.33333333, 19.        ])

In [39]:
np.ones(4,dtype=np.int8)

array([1, 1, 1, 1], dtype=int8)

In [42]:
np.ones(4,dtype=np.float64)

array([1., 1., 1., 1.])

## 2D Array

In [16]:
b = np.array([[5,3,4,6,],[5,5,5,5,],[5,5,5,5,],])
b

array([[5, 3, 4, 6],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [17]:
len(b)

3

In [18]:
b[0]

array([5, 3, 4, 6])

In [19]:
b[0:]

array([[5, 3, 4, 6],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [20]:
b[0][1]

3

In [28]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.empty([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

## 3D Array

In [43]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Numpy Practice Session

In [52]:
food = np.array(['pakora','somosa','biryani'])
food

array(['pakora', 'somosa', 'biryani'], dtype='<U7')

In [53]:
type(food)

numpy.ndarray

In [54]:
food.dtype

dtype('<U7')

In [55]:
food[2]

'biryani'

In [56]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [57]:
len(price)

3

In [61]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [60]:
#empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [62]:
#range
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
#specify 
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [64]:
#specify interval
np.arange(2,19,3)

array([ 2,  5,  8, 11, 14, 17])

In [66]:
#table of 5
np.arange(7,71,7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [67]:
# line space
np.linspace(2,10,4)

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [68]:
np.ones(5,dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

# Array Functions

In [70]:
a = np.array([5,21,43,4,90,5.3,1.3,4.5,90,87,45])
a

array([ 5. , 21. , 43. ,  4. , 90. ,  5.3,  1.3,  4.5, 90. , 87. , 45. ])

In [72]:
a.sort()
a

array([ 1.3,  4. ,  4.5,  5. ,  5.3, 21. , 43. , 45. , 87. , 90. , 90. ])

In [74]:
b = np.array([.7,4.3,4,6,8,43,2,1,2])
b

array([ 0.7,  4.3,  4. ,  6. ,  8. , 43. ,  2. ,  1. ,  2. ])

In [76]:
b.sort()
b

array([ 0.7,  1. ,  2. ,  2. ,  4. ,  4.3,  6. ,  8. , 43. ])

In [80]:
np.concatenate((a,b))

array([ 1.3,  4. ,  4.5,  5. ,  5.3, 21. , 43. , 45. , 87. , 90. , 90. ,
        0.7,  1. ,  2. ,  2. ,  4. ,  4.3,  6. ,  8. , 43. ])

# 2D Array

In [81]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
y = np.array([[9,8,7],[6,5,4]])
y

array([[9, 8, 7],
       [6, 5, 4]])

In [83]:
np.concatenate((x,y),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7],
       [6, 5, 4]])

In [84]:
np.concatenate((x,y),axis=1)

array([[1, 2, 3, 9, 8, 7],
       [4, 5, 6, 6, 5, 4]])

In [86]:
a=np.array([
    [[1,2,3],[4,5,6]],
    [[3,2,1],[6,5,4]],
    [[0,9,8],[8,9,0]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [6, 5, 4]],

       [[0, 9, 8],
        [8, 9, 0]]])

In [89]:
a.ndim

3

In [92]:
#shape
a.shape

(3, 2, 3)

In [93]:
# size
a.size

18

In [87]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
# dimensions
b.ndim

2

In [90]:
# shape
b.shape

(3, 3)

In [91]:
# size
b.size

9

In [95]:
# convert 1D array into 2D array
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
z = np.arange(1,10)
z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
# Row wise 2D array
s = z[np.newaxis,:]
s

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# Column wise 2D Array
d = z[np.newaxis]